# Generated by Django 3.2.9 on 2021-12-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211215_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='userprofile/default.jpg', max_length=254, upload_to='userprofile/', verbose_name='Image'),
        ),
    ]
