# Generated by Django 3.2.9 on 2021-12-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='media/default.jpg', max_length=254, upload_to='media/', verbose_name='Image'),
        ),
    ]
