# Generated by Django 3.2.9 on 2021-12-09 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='disliked_people',
            field=models.ManyToManyField(related_name='moviedislikedpeople', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movies',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='liked_people',
            field=models.ManyToManyField(related_name='movielikedpeople', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='disliked_people',
            field=models.ManyToManyField(related_name='dislikedpeople', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='liked_people',
            field=models.ManyToManyField(related_name='likedpeople', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movies.directors'),
        ),
        migrations.CreateModel(
            name='TvseriesLikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.BooleanField()),
                ('tvseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvprofile', to='movies.tvseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvlikedislike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieLikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.BooleanField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieprofile', to='movies.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movielikedislike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
