# Generated by Django 3.2.9 on 2021-12-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211209_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielikedislike',
            name='like_or_dislike',
        ),
        migrations.RemoveField(
            model_name='tvserieslikedislike',
            name='like_or_dislike',
        ),
        migrations.AddField(
            model_name='movielikedislike',
            name='dislike',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='movielikedislike',
            name='like',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='tvserieslikedislike',
            name='dislike',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='tvserieslikedislike',
            name='like',
            field=models.BooleanField(default=0),
        ),
    ]
