# Generated by Django 3.2.9 on 2021-12-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20211215_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='disliked_people',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='liked_people',
        ),
        migrations.RemoveField(
            model_name='tvseries',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='tvseries',
            name='disliked_people',
        ),
        migrations.RemoveField(
            model_name='tvseries',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='tvseries',
            name='liked_people',
        ),
    ]
