# Generated by Django 3.2.9 on 2021-12-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211220_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='generes',
            field=models.ManyToManyField(related_name='movie_genere', to='movies.Generes'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.ManyToManyField(related_name='movie_language', to='movies.Language'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='platform',
            field=models.ManyToManyField(related_name='movie_onlineplatform', to='movies.OnlinePlatform'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='starring',
            field=models.ManyToManyField(related_name='movie_starring', to='movies.Actors'),
        ),
    ]
